name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install
        run: |
          uv venv
          uv sync
      - name: Run
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          NORMALIZER_MODEL_BASE: "google/gemma-3-1b-it"
          REWARDS_MODEL_BASE: "google/gemma-3-1b-it"
        run: |
          source .venv/bin/activate
          pytest
